# Generated by Django 4.0 on 2022-05-06 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SellerProducts',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('price', models.FloatField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('discount', models.FloatField(blank=True, null=True)),
                ('availability', models.IntegerField(blank=True, db_column='Availability', null=True)),
            ],
            options={
                'db_table': 'seller_products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sellers',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'sellers',
                'managed': False,
            },
        ),
    ]
